// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZUhfnYxXK91bD-0TjyoTLok8XrlDWHhM',
    appId: '1:768144838449:web:583aec47b9388db229ea10',
    messagingSenderId: '768144838449',
    projectId: 'flutter-demo-1a315',
    authDomain: 'flutter-demo-1a315.firebaseapp.com',
    databaseURL: 'https://flutter-demo-1a315-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-1a315.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuy9kh8dIXjdAc-gb_43nqc3uTeKZ9lSY',
    appId: '1:768144838449:android:be80921fd7fedc9629ea10',
    messagingSenderId: '768144838449',
    projectId: 'flutter-demo-1a315',
    databaseURL: 'https://flutter-demo-1a315-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-1a315.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApqgzMBpYibgMTyf1XBosZ2eIDyuaZq8Y',
    appId: '1:768144838449:ios:1cf93ae711c504a229ea10',
    messagingSenderId: '768144838449',
    projectId: 'flutter-demo-1a315',
    databaseURL: 'https://flutter-demo-1a315-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-1a315.appspot.com',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApqgzMBpYibgMTyf1XBosZ2eIDyuaZq8Y',
    appId: '1:768144838449:ios:ee30b9e7bdf9fc0a29ea10',
    messagingSenderId: '768144838449',
    projectId: 'flutter-demo-1a315',
    databaseURL: 'https://flutter-demo-1a315-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-demo-1a315.appspot.com',
    iosBundleId: 'com.example.shoppingListApp.RunnerTests',
  );
}
